# Generated by Django 5.1.11 on 2025-09-06 13:33

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='social_image',
            new_name='banner_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='appear_in_search_results',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='listing_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='listing_summary',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='listing_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='social_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='register_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='register_link_url',
            field=models.URLField(blank=True, help_text='Destination for the Register button (e.g. /reg/ or /accounts/signup/)'),
        ),
    ]
