# Generated by Django 5.1.11 on 2025-09-06 11:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printshopitempage',
            name='short_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
