# Generated by Django 5.1.11 on 2025-09-05 11:03

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Short blurb shown above the list.')),
                ('paginate_by', models.PositiveIntegerField(default=10, help_text='Items per page.')),
                ('banner_image', models.ForeignKey(blank=True, help_text='Hero image for the Processes landing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProcessPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Publication date')),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown on index. If blank, first part of body is used.')),
                ('body', wagtail.fields.RichTextField()),
                ('banner_image', models.ForeignKey(blank=True, help_text='Optional hero image on the process page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
                ('thumbnail', models.ForeignKey(blank=True, help_text='Thumbnail used on Processes listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
