# Generated by Django 5.1.11 on 2025-09-05 11:15

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processpage',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='processpage',
            name='sections',
            field=wagtail.fields.StreamField([('h2', 1), ('paragraph', 2), ('collapsible', 7), ('full_width_image', 10), ('image_text_row', 13), ('wrapped_image_text', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Heading (H2)'}), 1: ('wagtail.blocks.StructBlock', [[('text', 0)]], {}), 2: ('processes.blocks.ParagraphBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Shown on the toggle button'}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Start expanded?', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional ID for collapse target; autogenerated if empty', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 3), ('body', 4), ('start_open', 5), ('slug', 6)]], {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.CharBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 8), ('caption', 9)]], {}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('4', '1/3'), ('3', '1/4'), ('6', '1/2')], 'help_text': 'Bootstrap column width for image on md+ (12 grid).'}), 13: ('wagtail.blocks.StructBlock', [[('image', 8), ('heading', 9), ('text', 4), ('image_position', 11), ('image_fraction', 12)]], {}), 14: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('start', 'Left'), ('end', 'Right')]}), 15: ('wagtail.blocks.IntegerBlock', (), {'default': 33, 'max_value': 90, 'min_value': 10}), 16: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul']}), 17: ('wagtail.blocks.StructBlock', [[('image', 8), ('float_side', 14), ('width_percent', 15), ('text', 16)]], {})}),
        ),
        migrations.AlterField(
            model_name='processpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AlterField(
            model_name='processpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='processpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
    ]
