# Generated by Django 5.1.11 on 2025-09-05 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('processes', '0002_remove_processpage_excerpt_processpage_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processpage',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary shown on the Processes index.'),
        ),
        migrations.AlterField(
            model_name='processpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, help_text='Thumbnail used on Processes listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
    ]
