# Generated by Django 5.1.11 on 2025-09-05 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, help_text='Optional hero image on the article page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, help_text='Square/landscape thumbnail for listings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
    ]
