# Generated by Django 5.1.11 on 2025-09-05 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpage_banner_image_alter_blogpage_thumbnail'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, help_text='Hero image for the blog landing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage'),
        ),
    ]
