# Generated by Django 5.1.11 on 2025-09-05 10:04

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogindexpage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='blog_pages', to='blog.blogcategory'),
        ),
    ]
