from wagtail import blocks
from wagtail.images.blocks import ImageChooserBlock

class Heading2Block(blocks.StructBlock):
    text = blocks.CharBlock(label="Heading (H2)")
    class Meta:
        icon = "title"
        template = "processes/blocks/heading2.html"

class ParagraphBlock(blocks.RichTextBlock):
    class Meta:
        icon = "doc-full"
        template = "processes/blocks/paragraph.html"
        features = ["h2", "h3", "bold", "italic", "link", "ol", "ul", "hr", "code"]

class CollapsibleBlock(blocks.StructBlock):
    title = blocks.CharBlock(help_text="Shown on the toggle button")
    body = blocks.RichTextBlock(features=["bold", "italic", "link", "ol", "ul"])
    start_open = blocks.BooleanBlock(required=False, default=False, help_text="Start expanded?")
    slug = blocks.CharBlock(required=False, help_text="Optional ID for collapse target; autogenerated if empty")
    class Meta:
        icon = "arrow-down"
        template = "processes/blocks/collapsible.html"

class FullWidthImageBlock(blocks.StructBlock):
    image = ImageChooserBlock()
    caption = blocks.CharBlock(required=False)
    class Meta:
        icon = "image"
        template = "processes/blocks/fullwidth_image.html"

class ImageTextRowBlock(blocks.StructBlock):
    image = ImageChooserBlock()
    heading = blocks.CharBlock(required=False)
    text = blocks.RichTextBlock(features=["bold", "italic", "link", "ol", "ul"])
    image_position = blocks.ChoiceBlock(choices=[("left","Left"),("right","Right")], default="left")
    image_fraction = blocks.ChoiceBlock(
        choices=[("4","1/3"),("3","1/4"),("6","1/2")], default="4",
        help_text="Bootstrap column width for image on md+ (12 grid)."
    )
    class Meta:
        icon = "placeholder"
        template = "processes/blocks/image_text_row.html"

class WrappedImageTextBlock(blocks.StructBlock):
    image = ImageChooserBlock()
    float_side = blocks.ChoiceBlock(choices=[("start","Left"),("end","Right")], default="start")
    width_percent = blocks.IntegerBlock(default=33, min_value=10, max_value=90)
    text = blocks.RichTextBlock(features=["h2","h3","bold","italic","link","ol","ul"])
    class Meta:
        icon = "collapse-down"
        template = "processes/blocks/wrapped_image_text.html"
