# Generated by Django 5.1.12 on 2025-09-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='Ireland', max_length=100),
        ),
    ]
