# Generated by Django 5.1.11 on 2025-09-05 12:41

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Shown centered under the title.')),
                ('sections', wagtail.fields.StreamField([('resource', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Small logo/icon for the resource', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short description shown under the title', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'label': 'Link URL'}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Explore', 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Open link in a new tab', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('summary', 2), ('url', 3), ('link_label', 4), ('open_in_new_tab', 5)]], {})})),
                ('banner_image', models.ForeignKey(blank=True, help_text='Hero image for the Resources page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.customimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
